Scalar : 0 차원 ex) 0, 1 ,2<br>
Vector , Matrix, Tensor

In [8]:
import numpy as np

## 1 차원

In [9]:
arr = np.array([5])
arr

array([5])

In [11]:
arr.shape

(1,)

In [12]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [13]:
arr.shape

(3,)

## 2차원

In [14]:
arr = np.array([[1, 2, 3]])
arr.shape

(1, 3)

In [15]:
arr = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
arr.shape

(3, 3)

## 다차원

In [25]:
# 3차원
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
])
arr.shape

(1, 2, 3)

array의 dtype을 본다.

In [26]:
arr.dtype

dtype('int32')

astype()으로 datatype을 변환 가능

In [27]:
arr.astype('float32') #uint8, int32...

array([[[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)